Fix for new hoomd dlext
SSAGESLabs/PySAGES pull request #144
Opened 2022-06-17 15:38 UTC by InnocentBug

Adjustments to PySAGES that are required with the hoomd-dlext backend.

2022-06-17 17:01 UTC, pabloferz reviewed
I the constructor takes a `SystemView`

2022-06-17 17:01 UTC, pabloferz commented on pysages/backends/hoomd.py
>      def __init__(self, sysdef, method_bundle, bias, dt, callback: Callable):
```suggestion
    def __init__(self, sysview, method_bundle, bias, dt, callback: Callable):
```

2022-06-17 17:04 UTC, InnocentBug commented on pysages/backends/hoomd.py
> +            context.system_definition, method_bundle, sync_and_bias, context.integrator.dt, callback
solved differently.

2022-06-17 17:05 UTC, InnocentBug commented on pysages/backends/hoomd.py
>      def __init__(self, sysdef, method_bundle, bias, dt, callback: Callable):
solved

2022-06-17 17:33 UTC, pabloferz commented on pysages/backends/hoomd.py
> +        super().__init__(sysview, python_update, AccessMode.Read, default_location())
```suggestion
        super().__init__(sysview, python_update, default_location(), AccessMode.Read)
```

2022-06-21 19:28 UTC, pabloferz requested changes
There's still a spelling commit hanging around.

2022-06-21 19:29 UTC, InnocentBug commented
I reversed the spelling thing

2022-06-21 19:58 UTC, pabloferz approved these changes

2022-06-21 19:58 UTC, merged