New nn API
SSAGESLabs/PySAGES pull request #42
Opened 2021-09-02 21:24 UTC by pabloferz

This is a full rewrite of the `nn` submodule. The idea is to merge this in, then switch all the methods that use neural nets to use this instead and then to remove the previous submodule.

2021-10-04 22:22 UTC, InnocentBug requested changes
Some of the implementations confuse me.
But maybe that is my limited understanding of how dispatch is supposed to be used.
Or some documentation could help.

I also think, that an example that uses the code would make it easier for users to get into the code.

2021-10-04 22:22 UTC, InnocentBug commented on pysages/_nn/objectives.py
> +# Losses
Are these all abstract classes, or why are they all defined here, but not implemented.
I am a little confused here.

2021-10-04 22:22 UTC, InnocentBug commented on pysages/_nn/objectives.py
> +def build_cost_function(model, loss: Loss, reg: Regularizer):
this function overloading is a bit confusing to me.
Is it really the best way to have overloaded `build_cost_function` with different number of arguments.
Wouldn't it make sense to have a different name for the ones that take a model?

2021-10-04 22:22 UTC, InnocentBug commented on pysages/_nn/objectives.py
> +    cost = build_cost_function(loss, reg)
I don't understand, why this is generated here.
Does it have a side effects?
I don't see where `cost` would be used after.

2021-10-04 22:22 UTC, InnocentBug commented on pysages/_nn/objectives.py
> +def build_cost_function(model, loss: Sobolev1Loss, reg: Regularizer):
I guess, for all of them. It wouldn't hurt to have a doc string, that explains what the model is and how it is implemented here.

2021-11-03 18:14 UTC, InnocentBug approved these changes
I can't really test it. But it looks good.

2021-11-03 20:41 UTC, pabloferz commented
I'll add a README and tests in a follow up PR.

2021-11-03 20:42 UTC, merged